---
- name: Install IPA Server, enable and start it, and open firewall ports
  hosts: idm
  gather_facts: false
  tasks:
    - name: Install IPA server and DNS packages
      ansible.builtin.dnf:
        name:
          - ipa-server
          - ipa-server-dns
        state: present

    - name: Open ldap ports
      ansible.posix.firewalld:
        service: freeipa-ldap
        state: enabled
        permanent: true
        immediate: true

    - name: Open ldaps ports
      ansible.posix.firewalld:
        service: freeipa-ldaps
        state: enabled
        permanent: true
        immediate: true

    - name: Open ntp ports
      ansible.posix.firewalld:
        service: ntp
        state: enabled
        permanent: true
        immediate: true

    - name: Open dns ports
      ansible.posix.firewalld:
        service: dns
        state: enabled
        permanent: true
        immediate: true

# removed because the server hasn't been configured yet   
#    - name: Enable the service
#      ansible.builtin.systemd_service:
#        name: ipa
#        enabled: true
#        state: started
